# -*- coding: utf-8 -*-
"""Strategy specifications and authored text for FS03-FS12 (sort strategies; FS05 monkey is separate)."""

COMMON_REFS = [
    "Newey, W. & West, K. (1987). A simple, positive semi-definite, heteroskedasticity and autocorrelation consistent covariance matrix. *Econometrica*, 55(3), 703–708.",
    "Politis, D. & Romano, J. (1994). The stationary bootstrap. *Journal of the American Statistical Association*, 89(428), 1303–1313.",
    "Bailey, D. & López de Prado, M. (2012). The Sharpe ratio efficient frontier. *Journal of Risk*, 15(2), 3–44.",
    "Jensen, T. I., Kelly, B. & Pedersen, L. H. (2023). Is there a replication crisis in finance? *Journal of Finance*, 78(5), 2465–2518.",
    "Fama, E. & French, K. (2015). A five-factor asset pricing model. *Journal of Financial Economics*, 116(1), 1–22.",
    "McLean, R. D. & Pontiff, J. (2016). Does academic research destroy stock return predictability? *Journal of Finance*, 71(1), 5–32.",
    "Novy-Marx, R. & Velikov, M. (2016). A taxonomy of anomalies and their trading costs. *Review of Financial Studies*, 29(1), 104–147.",
    "Barroso, P. & Santa-Clara, P. (2015). Momentum has its moments. *Journal of Financial Economics*, 116(1), 111–120.",
    "Moreira, A. & Muir, T. (2017). Volatility-managed portfolios. *Journal of Finance*, 72(4), 1611–1644.",
    "Treynor, J. & Mazuy, K. (1966). Can mutual funds outguess the market? *Harvard Business Review*, 44(4), 131–136.",
]

S = {
"FS03": dict(slug="fs03-momentum", stem="FS03_Momentum", title="Momentum", sub="Buy last year's winners, sell last year's losers", sig="mom", long_high=True, construction="sort", mirror="r1",
    origin="Jegadeesh & Titman (1993)", family="Momentum & trend", style="Cross-sectional momentum (Carhart's UMD, AQR's momentum)",
    good="winners (highest 12-1 return)", bad="losers (lowest 12-1 return)",
    claim="Stocks that did best over the past year keep outperforming the worst over the next months. Jegadeesh & Titman (1993) found about 1% a month for US stocks in 1965–1989; Asness, Moskowitz & Pedersen (2013) found it in every major equity market and asset class.",
    rule_rows=[("Signal", "Past 3–12 month return; the classic 12-1 skips the latest month", "Return from month t−11 to t−1 (skip month t)"),
               ("Portfolio", "Decile or tercile long/short, 1–12 month holding", "Extreme quantile L/S, one-month holding, monthly rebalance"),
               ("Weighting", "Equal or value weighted", "Equal weighted")],
    signal_text="MOM<sub>i,t</sub> = P<sub>i,t−1</sub> / P<sub>i,t−12</sub> − 1 on total-return prices; the most recent month is skipped to avoid the one-month reversal.",
    rationale="Behavioural: investors under-react to news and then herd (Barberis, Shleifer & Vishny 1998; Hong & Stein 1999); the disposition effect slows the price response (Grinblatt & Han 2005). Risk stories exist but explain little.",
    publication="Jegadeesh & Titman 1993 (data to 1989); Carhart 1997 factor; known crash risk after market rebounds (Daniel & Moskowitz 2016)",
    refs=["Jegadeesh, N. & Titman, S. (1993). Returns to buying winners and selling losers. *Journal of Finance*, 48(1), 65–91.",
          "Carhart, M. (1997). On persistence in mutual fund performance. *Journal of Finance*, 52(1), 57–82.",
          "Asness, C., Moskowitz, T. & Pedersen, L. H. (2013). Value and momentum everywhere. *Journal of Finance*, 68(3), 929–985.",
          "Daniel, K. & Moskowitz, T. (2016). Momentum crashes. *Journal of Financial Economics*, 122(2), 221–247.",
          "Barberis, N., Shleifer, A. & Vishny, R. (1998). A model of investor sentiment. *Journal of Financial Economics*, 49(3), 307–343.",
          "Hong, H. & Stein, J. (1999). A unified theory of underreaction, momentum trading, and overreaction in asset markets. *Journal of Finance*, 54(6), 2143–2184.",
          "Grinblatt, M. & Han, B. (2005). Prospect theory, mental accounting, and momentum. *Journal of Financial Economics*, 78(2), 311–339."],
    gaps=[]),
"FS04": dict(slug="fs04-low-volatility", stem="FS04_Low_Volatility", title="Low volatility", sub="Do calm stocks beat exciting ones?", sig="vol252", long_high=False, construction="sort", mirror="max1",
    origin="Haugen & Heins (1975); Blitz & van Vliet (2007)", family="Low risk", style="Defensive / low-risk anomaly",
    good="calmest stocks (lowest 252-day volatility)", bad="most volatile stocks",
    claim="Low-volatility stocks earn about the same or more than high-volatility stocks, so their risk-adjusted return is far higher, contradicting the CAPM. Blitz & van Vliet (2007) documented it globally for 1986–2006; Ang, Hodrick, Xing & Zhang (2006) for idiosyncratic volatility.",
    rule_rows=[("Signal", "Past 1–3 year volatility (weekly or daily returns)", "252-day volatility of daily total returns"),
               ("Portfolio", "Decile or quintile; often long-only low-vol", "Extreme quantile L/S and the low-vol leg long-only, monthly"),
               ("Weighting", "Equal or value weighted", "Equal weighted")],
    signal_text="VOL<sub>i,t</sub> = standard deviation of daily returns over the 252 trading days to month-end t (at least 200 days).",
    rationale="Leverage constraints push investors into high-beta, high-volatility stocks (Black 1972; Frazzini & Pedersen 2014); benchmarked managers cannot exploit it without tracking error (Baker, Bradley & Wurgler 2011); lottery preferences (Bali, Cakici & Whitelaw 2011).",
    publication="Haugen & Heins 1975; Ang et al. 2006; Blitz & van Vliet 2007; widely sold as min-vol ETFs since 2011",
    refs=["Haugen, R. & Heins, A. J. (1975). Risk and the rate of return on financial assets: Some old wine in new bottles. *Journal of Financial and Quantitative Analysis*, 10(5), 775–784.",
          "Ang, A., Hodrick, R., Xing, Y. & Zhang, X. (2006). The cross-section of volatility and expected returns. *Journal of Finance*, 61(1), 259–299.",
          "Blitz, D. & van Vliet, P. (2007). The volatility effect. *Journal of Portfolio Management*, 34(1), 102–113.",
          "Baker, M., Bradley, B. & Wurgler, J. (2011). Benchmarks as limits to arbitrage: Understanding the low-volatility anomaly. *Financial Analysts Journal*, 67(1), 40–54.",
          "Frazzini, A. & Pedersen, L. H. (2014). Betting against beta. *Journal of Financial Economics*, 111(1), 1–25."],
    gaps=[]),
"FS06": dict(slug="fs06-seasonality", stem="FS06_Seasonality", title="Same-month seasonality", sub="Do stocks repeat their best calendar month?", sig="seas", long_high=True, construction="sort", mirror="mom",
    origin="Heston & Sadka (2008)", family="Calendar & seasonality", style="Return seasonality (cross-sectional)",
    good="stocks with the highest past returns in the coming calendar month", bad="stocks with the lowest",
    claim="A stock that did well relative to others in, say, March tends to do well again in March in later years, at annual lags up to 20 years. Heston & Sadka (2008) found it in US stocks 1965–2002; Keloharju, Linnainmaa & Nyberg (2016) found the same across markets and asset classes.",
    rule_rows=[("Signal", "Average return in the same calendar month over the past 1–20 years", "Average return in the coming calendar month over all prior years available (1 year in 2013, 13 by 2026)"),
               ("Portfolio", "Decile L/S, one month", "Extreme quantile L/S, one month"),
               ("Weighting", "Equal weighted", "Equal weighted")],
    signal_text="SEAS<sub>i,t</sub> = mean of r<sub>i,m</sub> over the months m with the same calendar month as t+1 in earlier years.",
    rationale="Recurring demand and information flows tied to the calendar (earnings seasons, dividend timing, fund flows); Keloharju et al. (2016) argue it reflects seasonal variation in risk premia.",
    publication="Heston & Sadka 2008; Keloharju, Linnainmaa & Nyberg 2016",
    refs=["Heston, S. & Sadka, R. (2008). Seasonality in the cross-section of stock returns. *Journal of Financial Economics*, 87(2), 418–445.",
          "Keloharju, M., Linnainmaa, J. & Nyberg, P. (2016). Return seasonalities. *Journal of Finance*, 71(4), 1557–1590."],
    gaps=["Price history starts in 2011–2012, so the signal averages 1 prior year in 2013 and at most 13 by 2026; Heston & Sadka use up to 20. The early years test a much noisier signal than the paper's."]),
"FS07": dict(slug="fs07-size", stem="FS07_Size", title="Size", sub="Do smaller companies beat bigger ones?", sig="size", long_high=False, construction="sort", mirror="ivol",
    origin="Banz (1981)", family="Size", style="Size premium (Fama-French SMB)",
    good="smallest names in the universe", bad="largest names",
    claim="Small companies earn higher returns than large ones. Banz (1981) found it in US stocks 1936–1975; it became Fama & French's SMB factor, but has been weak since the early 1980s unless junk stocks are controlled for (Asness et al. 2018).",
    rule_rows=[("Signal", "Market capitalisation", "US: market cap (Sharadar). Elsewhere: 63-day average traded value (price × volume), a proxy"),
               ("Portfolio", "Size deciles or SMB (2×3)", "Extreme quantile L/S within the universe, monthly"),
               ("Weighting", "Value weighted", "Equal weighted")],
    signal_text="SIZE<sub>i,t</sub> = log market cap (US) or log 63-day average traded value (elsewhere) at month-end t; World ranks within each region first.",
    rationale="Risk (distress, illiquidity; Fama & French 1993) or mispricing; much of the historical premium came from the smallest, least liquid stocks and January.",
    publication="Banz 1981; Fama & French 1992–93; 'Is size dead?' (van Dijk 2011); 'Size matters, if you control your junk' (Asness et al. 2018)",
    refs=["Banz, R. (1981). The relationship between return and market value of common stocks. *Journal of Financial Economics*, 9(1), 3–18.",
          "Fama, E. & French, K. (1993). Common risk factors in the returns on stocks and bonds. *Journal of Financial Economics*, 33(1), 3–56.",
          "van Dijk, M. (2011). Is size dead? A review of the size effect in equity returns. *Journal of Banking & Finance*, 35(12), 3263–3274.",
          "Asness, C., Frazzini, A., Israel, R., Moskowitz, T. & Pedersen, L. H. (2018). Size matters, if you control your junk. *Journal of Financial Economics*, 129(3), 479–509."],
    gaps=["No shares outstanding outside the US: size is proxied by traded value, which also measures liquidity and turnover.",
          "The universes are blue chips; the classic size premium lives in micro and small caps, which are excluded by construction."]),
"FS08": dict(slug="fs08-short-term-reversal", stem="FS08_Short_Term_Reversal", title="Short-term reversal", sub="Buy last month's losers, sell last month's winners", sig="r1", long_high=False, construction="sort", mirror="mom",
    origin="Jegadeesh (1990); Lehmann (1990)", family="Reversal & bottom-fishing", style="One-month reversal (liquidity provision)",
    good="last month's losers", bad="last month's winners",
    claim="Stocks with the worst returns last month outperform those with the best returns next month. Jegadeesh (1990) and Lehmann (1990) documented it for US stocks; it is large before costs and famously expensive to trade.",
    rule_rows=[("Signal", "Previous month's (or week's) return", "Return in month t"),
               ("Portfolio", "Decile L/S, one month", "Extreme quantile L/S, one month"),
               ("Weighting", "Equal or value weighted", "Equal weighted")],
    signal_text="R1<sub>i,t</sub> = total return of stock i in month t.",
    rationale="Compensation for providing liquidity to investors who trade on non-information (Nagel 2012); overreaction to short-term news.",
    publication="Jegadeesh 1990; Lehmann 1990; Nagel 2012 (reversal as liquidity provision)",
    refs=["Jegadeesh, N. (1990). Evidence of predictable behavior of security returns. *Journal of Finance*, 45(3), 881–898.",
          "Lehmann, B. (1990). Fads, martingales, and market efficiency. *Quarterly Journal of Economics*, 105(1), 1–28.",
          "Nagel, S. (2012). Evaporating liquidity. *Review of Financial Studies*, 25(7), 2005–2039."],
    gaps=[]),
"FS09": dict(slug="fs09-52-week-high", stem="FS09_52_Week_High", title="52-week high", sub="Do stocks near their high keep going?", sig="hi52", long_high=True, construction="sort", mirror="lo52",
    origin="George & Hwang (2004)", family="Momentum & trend", style="Anchoring momentum",
    good="stocks closest to their 52-week high", bad="stocks furthest below it",
    claim="Stocks trading close to their 52-week high outperform those far below it, and this nearness explains much of momentum. George & Hwang (2004) found it for US stocks 1963–2001; investors anchor on the high and under-react to good news near it.",
    rule_rows=[("Signal", "Price / 52-week high", "Total-return price / 252-day high at month-end t"),
               ("Portfolio", "Top 30% minus bottom 30%, 6-month holding", "Extreme quantile L/S, one-month holding"),
               ("Weighting", "Equal weighted", "Equal weighted")],
    signal_text="HI52<sub>i,t</sub> = P<sub>i,t</sub> / max(P<sub>i,t−251..t</sub>).",
    rationale="Anchoring: traders use the 52-week high as a reference and are reluctant to bid prices above it, so good news is absorbed slowly (George & Hwang 2004).",
    publication="George & Hwang 2004",
    refs=["George, T. & Hwang, C.-Y. (2004). The 52-week high and momentum investing. *Journal of Finance*, 59(5), 2145–2176."],
    gaps=["We hold for one month; George & Hwang hold for six. A longer holding period would cut turnover."]),
"FS10": dict(slug="fs10-betting-against-beta", stem="FS10_Betting_Against_Beta", title="Betting against beta", sub="Lever up the low-beta stocks, short the high-beta ones", sig="beta", long_high=False, construction="bab", mirror="max1",
    origin="Frazzini & Pedersen (2014)", family="Low risk", style="Defensive / betting against beta",
    good="low-beta stocks", bad="high-beta stocks",
    claim="Low-beta stocks have higher risk-adjusted returns than high-beta stocks. A portfolio that is long leveraged low-beta stocks and short de-leveraged high-beta stocks, beta-neutral, earned a large positive return in the US 1926–2012 and in 19 other markets (Frazzini & Pedersen 2014).",
    rule_rows=[("Signal", "Shrunk beta from 1-year volatility and 5-year correlation", "252-day beta vs the equal-weight universe (no shrinkage)"),
               ("Portfolio", "Rank-weighted legs above/below median beta, each scaled to beta 1", "Same construction"),
               ("Weighting", "Rank weights", "Rank weights")],
    signal_text="BAB<sub>t+1</sub> = r<sub>L</sub>/β<sub>L</sub> − r<sub>H</sub>/β<sub>H</sub>, with rank-weighted low- and high-beta legs (the net long cash is financed at the USD risk-free rate + 0.5% a year; the high-beta leg pays a size-tiered borrow fee).",
    rationale="Leverage-constrained investors buy high-beta stocks instead of levering the market, bidding them up (Black 1972; Frazzini & Pedersen 2014); lottery demand (Bali, Brown, Murray & Tang 2017).",
    publication="Black, Jensen & Scholes 1972; Frazzini & Pedersen 2014; critique by Novy-Marx & Velikov (2022) on construction and costs",
    refs=["Frazzini, A. & Pedersen, L. H. (2014). Betting against beta. *Journal of Financial Economics*, 111(1), 1–25.",
          "Black, F. (1972). Capital market equilibrium with restricted borrowing. *Journal of Business*, 45(3), 444–455.",
          "Bali, T. G., Brown, S., Murray, S. & Tang, Y. (2017). A lottery-demand-based explanation of the beta anomaly. *Journal of Financial and Quantitative Analysis*, 52(6), 2369–2397.",
          "Novy-Marx, R. & Velikov, M. (2022). Betting against betting against beta. *Journal of Financial Economics*, 143(1), 80–106."],
    gaps=["Financing uses the USD risk-free rate for all markets, which overstates the cost in EU and Denmark while their rates were negative (2015–21). Betas are raw, not shrunk."]),
"FS11": dict(slug="fs11-residual-momentum", stem="FS11_Residual_Momentum", title="Residual momentum", sub="Momentum without the market's ups and downs", sig="resmom", long_high=True, construction="sort", mirror="r1",
    origin="Blitz, Huij & Martens (2011)", family="Momentum & trend", style="Residual (idiosyncratic) momentum",
    good="stocks with the strongest stock-specific trend", bad="the weakest",
    claim="Ranking stocks on the part of their past return that the market does not explain gives a momentum strategy with about half the volatility and far smaller crashes than plain momentum (Blitz, Huij & Martens 2011, US 1930–2009).",
    rule_rows=[("Signal", "Sum of Fama-French 3-factor residuals t−12..t−2, over a 36-month window, divided by their volatility", "Market-model residuals over 24 months, same scaling"),
               ("Portfolio", "Decile L/S, one month", "Extreme quantile L/S, one month"),
               ("Weighting", "Equal weighted", "Equal weighted")],
    signal_text="RESMOM<sub>i,t</sub> = Σ ε<sub>i,t−11..t−1</sub> / σ(ε), from monthly regressions of r<sub>i</sub> on the equal-weight universe over the last 24 months.",
    rationale="Same under-reaction story as momentum, but removing the market (and factor) component avoids the time-varying beta that makes plain momentum crash (Grundy & Martin 2001; Daniel & Moskowitz 2016).",
    publication="Grundy & Martin 2001; Gutierrez & Pirinsky 2007; Blitz, Huij & Martens 2011",
    refs=["Blitz, D., Huij, J. & Martens, M. (2011). Residual momentum. *Journal of Empirical Finance*, 18(3), 506–521.",
          "Grundy, B. & Martin, J. S. (2001). Understanding the nature of the risks and the source of the rewards to momentum investing. *Review of Financial Studies*, 14(1), 29–78.",
          "Daniel, K. & Moskowitz, T. (2016). Momentum crashes. *Journal of Financial Economics*, 122(2), 221–247."],
    gaps=["Market-only residuals over 24 months (the paper uses Fama-French 3 factors over 36); stock-level factor loadings outside the US would need data we do not have. The first signals appear in early 2014."]),
"FS12": dict(slug="fs12-52-week-low", stem="FS12_52_Week_Low", title="Buy at the 52-week low", sub="Should you buy stocks at their yearly low?", sig="lo52", long_high=False, construction="sort", mirror="hi52",
    origin="Market folklore (bottom-fishing); tested against George & Hwang (2004)", family="Reversal & bottom-fishing", style="Contrarian / bottom-fishing",
    good="stocks closest to their 52-week low", bad="stocks furthest above it",
    claim="Folklore says stocks at their yearly low are bargains: 'buy low'. The academic evidence points the other way: stocks near their lows tend to keep underperforming (George & Hwang 2004), and in the series A10 Free Fallin' found knives rebound only in market-wide crashes.",
    rule_rows=[("Signal", "Folklore: buy at or near the 52-week low", "Total-return price / 252-day low; lowest = at the low"),
               ("Portfolio", "No standard rule", "Extreme quantile L/S (at the low minus far above), one month"),
               ("Weighting", "—", "Equal weighted")],
    signal_text="LO52<sub>i,t</sub> = P<sub>i,t</sub> / min(P<sub>i,t−251..t</sub>); the long leg holds the stocks with the lowest value (at the low).",
    rationale="Folklore: mean reversion and value. Evidence: momentum and anchoring (George & Hwang 2004) predict continued weakness; losers carry high beta and volatility.",
    publication="No academic origin; George & Hwang 2004 as the counter-claim; series A10 (Free Fallin')",
    refs=["George, T. & Hwang, C.-Y. (2004). The 52-week high and momentum investing. *Journal of Finance*, 59(5), 2145–2176.",
          "Jegadeesh, N. & Titman, S. (1993). Returns to buying winners and selling losers. *Journal of Finance*, 48(1), 65–91."],
    gaps=[]),
}
ORDER = ["FS03", "FS04", "FS06", "FS07", "FS08", "FS09", "FS10", "FS11", "FS12"]
